version: 2.1
executors:
  python-program-executor:
    docker:
      - image: "circleci/python:3.9.0"
      
# Final Project of Course SSW-567_A

jobs:
  # Main Program - Carmen Couzyn
  build_main_program:
    executor: python-program-executor
    steps:
      - checkout
      - run:
          name: "building"
          working_directory: ~/project/src
          command: |
            MRTD.py
            
  # Performance Testing - Yujun Kong
  build_perf_testing:
    executor: python-program-executor
    steps:
      - checkout
      - run:
          name: "building"
          working_directory: ~/project/src
          command: |
            pip install matplotlib
            python Perf_Testing.py
            
workflows:
  build:
    jobs:
      - build_main_program
      - build_perf_testing
